pipeline{
    agent any
    parameters{
       string(defaultValue: "Challenge3", description: "Type Deployment name", name: "deploymentName")
        choice(choices: ["EU-WEST-2A", "EU-WEST-2B", "EU-WEST-2C"], description: "Select which AZ?", name: "azName")
        booleanParam(defaultValue: false, description: "Confirm Deployment", name: "confirmDeployment")
    }
    stages{
        stage(completed){
            steps{
                echo "Deployment successfully done to: ${deploymentName} \n"
                echo "Regions successfully done to: ${azName} \n"
                echo "confirmed successfully done to: ${confirmDeployment}"
            }
        }
    }
}
