pipeline{
    agent any
    parameters{
        choice(choices: ["DEV", "QA", "PROD"], description: "Select Deployment name", name: "DeploymentName")
        choice(choices: ["EU-WEST-2A", "EU-WEST-2B", "EU-WEST-2C"], description: "Select which AZ?", name: "AZname")
    }
    stages{
        stage(completed){
            steps{
                echo "Deployment successfully done to: ${DeploymentName}"
            }
        }
    }
}
